
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgrwsbjqeghsscjovgdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncndzYmpxZWdoc3Njam92Z2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjkzOTksImV4cCI6MjA2NjM0NTM5OX0.GrQ4Wm2DZ1ooVbzS6k0yjRc7O9rkwJoVEdpd_jCrbFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// For backwards compatibility
export const getSupabaseClient = async () => supabase;
export const supabaseReady = Promise.resolve(supabase);
